### ISSUE TITLE
feat: ✨ Implement dark mode for components and documentation

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#147]
# Story

As a developer using the Synergy Design System, I would like to have support for dark mode in applications. The dark.css is already shipped, but should be applied when `color-schema` is set to `dark`.

# Todos:

- [x] The css files have to be adjusted to make them available in dark-mode.
- [x] The `dark.css` theme must be applied in `packages/docs/` storybook
- [x] The light/dark toggle of storybook must be configured to really set the `color-schema`
- [x] Documentation has to be adjusted for users.

# Acceptance criteria

- [x] toggle darkmode in storybook
- [x] update README how to toggle modes
- [x] all components shipped in darkmode should be validated
- [x] form demo should implement mode toggle
- [x] Chromatic should be able to create screenshots in light and dark mode

**Comment by klaarseSICKAG** [comment]
refers to https://github.com/SickDesignSystem/synergy/issues/139

**Comment by schilchSICKAG** [comment]
Is currently not planned for 1.0.0, but available as a preview on https://github.com/synergy-design-system/synergy-design-system/tree/feat/add-dark-mode-support.
