### ISSUE TITLE
fix: 🐛 Umbrella: SynPrioNav

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#644]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.9.0

# Component

The issue arises when using the following component(s): syn-prio-nav, syn-nav-item

# Description

This ticket acts as an umbrella ticket for all currently open problems that happen on `<syn-prio-nav>` and `<syn-nav-item>`

# Acceptance criteria

- [x] All DoD items successfully completed
- [x] All of the following tickets are fixed and tested in the branch:
- [x] #582
- [x] #631
- [x] #410
- [x] #409
- [x] #639

**Comment by schilchSICKAG** [comment]
@xkabylgSICKAG
Just for information
